title: Ju Feng ：
subtitle: program node
description: A robotic engineer, and also a software engineer
author: Jufeng wu
email: leowu102000@gmail.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl:
url: "https://jufengwu.github.io/"

# Social settings

linkedin_url:  https://www.linkedin.com/in/ju-feng-wu-71a0a8146/
github_url: https://github.com/JuFengWu


# Google Analytics Tracking ID goes here:
google_analytics: UA-145114924-1

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
