title: Ju Feng ：
subtitle: program node
description: A robotic engineer, and also a software engineer
author: Jufeng wu
email: leowu102000@gmail.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "/home"
url: "https://jufengwu.github.io/"


# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
