title: Your awesome title
subtitle: Your awesome subtitle
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Your Incredible Name
email: your-email@example.com
avatar: assets/images/avatar.jpg


baseurl: "" 
url: "https://jufengwu.github.io/"


# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
